# Generated by Django 2.2.6 on 2020-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street1', models.CharField(max_length=50)),
                ('street2', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('landmark', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
