# Generated by Django 2.2.6 on 2020-04-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_deliveryboy_item_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Info',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=20)),
                ('lat_long', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.DeliveryBoy')),
            ],
        ),
    ]
