# Generated by Django 2.2.6 on 2020-04-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Address')),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.OrderList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Users')),
            ],
        ),
    ]
