# Generated by Django 2.2.6 on 2020-04-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('quantity', models.IntegerField()),
                ('customer_status', models.CharField(default='pending', max_length=30)),
                ('delivery_boy_status', models.CharField(default='pending', max_length=30)),
                ('admin_status', models.CharField(default='pending', max_length=30)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Users')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Item')),
            ],
        ),
        migrations.CreateModel(
            name='BufferStock',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Address')),
            ],
        ),
        migrations.CreateModel(
            name='AllotedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.DeliveryBoy')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Vehicle_Info')),
            ],
        ),
    ]
