# Generated by Django 2.2.6 on 2020-04-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_allotedarea_bufferstock_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferstock',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bufferstock',
            name='item_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.Item'),
        ),
    ]
