# Generated by Django 2.2.6 on 2020-04-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20200409_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BufferStock',
        ),
    ]
