# Generated by Django 2.2.6 on 2020-04-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_bufferstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Address')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Item')),
            ],
        ),
    ]
